/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingConfirmRouteImport } from './routes/onboarding.confirm'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedProcessMapRouteImport } from './routes/_authenticated/process-map'
import { Route as AuthenticatedNodeErRouteImport } from './routes/_authenticated/node-er'
import { Route as AuthenticatedModelerRouteImport } from './routes/_authenticated/modeler'
import { Route as AuthenticatedEntitiesRouteImport } from './routes/_authenticated/entities'
import { Route as AuthenticatedEngineRouteImport } from './routes/_authenticated/engine'
import { Route as AuthenticatedEncyclopediaRouteImport } from './routes/_authenticated/encyclopedia'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedAiSuggestRouteImport } from './routes/_authenticated/ai-suggest'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicValidateEmailRouteImport } from './routes/api/public/validate-email'
import { Route as ApiPublicSendWelcomeConfirmRouteImport } from './routes/api/public/send-welcome-confirm'
import { Route as ApiPublicNotifyNewSignupRouteImport } from './routes/api/public/notify-new-signup'
import { Route as ApiPublicConfirmSignupRouteImport } from './routes/api/public/confirm-signup'
import { Route as ApiPublicAcceptInviteRouteImport } from './routes/api/public/accept-invite'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTenantRouteImport } from './routes/_authenticated/admin.tenant'
import { Route as AuthenticatedAdminNodeTaxonomyRouteImport } from './routes/_authenticated/admin.node-taxonomy'
import { Route as AuthenticatedAdminGovernanceRouteImport } from './routes/_authenticated/admin.governance'
import { Route as AuthenticatedAdminEntitiesErRouteImport } from './routes/_authenticated/admin.entities-er'
import { Route as AuthenticatedAdminControlCenterRouteImport } from './routes/_authenticated/admin.control-center'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedHierarchyLevelIdRouteImport } from './routes/_authenticated/hierarchy.$level.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConfirmRoute = OnboardingConfirmRouteImport.update({
  id: '/onboarding/confirm',
  path: '/onboarding/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessMapRoute = AuthenticatedProcessMapRouteImport.update({
  id: '/process-map',
  path: '/process-map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNodeErRoute = AuthenticatedNodeErRouteImport.update({
  id: '/node-er',
  path: '/node-er',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelerRoute = AuthenticatedModelerRouteImport.update({
  id: '/modeler',
  path: '/modeler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntitiesRoute = AuthenticatedEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEngineRoute = AuthenticatedEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEncyclopediaRoute =
  AuthenticatedEncyclopediaRouteImport.update({
    id: '/encyclopedia',
    path: '/encyclopedia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiSuggestRoute = AuthenticatedAiSuggestRouteImport.update({
  id: '/ai-suggest',
  path: '/ai-suggest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicValidateEmailRoute = ApiPublicValidateEmailRouteImport.update({
  id: '/api/public/validate-email',
  path: '/api/public/validate-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendWelcomeConfirmRoute =
  ApiPublicSendWelcomeConfirmRouteImport.update({
    id: '/api/public/send-welcome-confirm',
    path: '/api/public/send-welcome-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyNewSignupRoute =
  ApiPublicNotifyNewSignupRouteImport.update({
    id: '/api/public/notify-new-signup',
    path: '/api/public/notify-new-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConfirmSignupRoute = ApiPublicConfirmSignupRouteImport.update({
  id: '/api/public/confirm-signup',
  path: '/api/public/confirm-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcceptInviteRoute = ApiPublicAcceptInviteRouteImport.update({
  id: '/api/public/accept-invite',
  path: '/api/public/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantRoute =
  AuthenticatedAdminTenantRouteImport.update({
    id: '/admin/tenant',
    path: '/admin/tenant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNodeTaxonomyRoute =
  AuthenticatedAdminNodeTaxonomyRouteImport.update({
    id: '/admin/node-taxonomy',
    path: '/admin/node-taxonomy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGovernanceRoute =
  AuthenticatedAdminGovernanceRouteImport.update({
    id: '/admin/governance',
    path: '/admin/governance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEntitiesErRoute =
  AuthenticatedAdminEntitiesErRouteImport.update({
    id: '/admin/entities-er',
    path: '/admin/entities-er',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminControlCenterRoute =
  AuthenticatedAdminControlCenterRouteImport.update({
    id: '/admin/control-center',
    path: '/admin/control-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHierarchyLevelIdRoute =
  AuthenticatedHierarchyLevelIdRouteImport.update({
    id: '/hierarchy/$level/$id',
    path: '/hierarchy/$level/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai-suggest': typeof AuthenticatedAiSuggestRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/encyclopedia': typeof AuthenticatedEncyclopediaRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/modeler': typeof AuthenticatedModelerRoute
  '/node-er': typeof AuthenticatedNodeErRoute
  '/process-map': typeof AuthenticatedProcessMapRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/admin/control-center': typeof AuthenticatedAdminControlCenterRoute
  '/admin/entities-er': typeof AuthenticatedAdminEntitiesErRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/node-taxonomy': typeof AuthenticatedAdminNodeTaxonomyRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/confirm-signup': typeof ApiPublicConfirmSignupRoute
  '/api/public/notify-new-signup': typeof ApiPublicNotifyNewSignupRoute
  '/api/public/send-welcome-confirm': typeof ApiPublicSendWelcomeConfirmRoute
  '/api/public/validate-email': typeof ApiPublicValidateEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/hierarchy/$level/$id': typeof AuthenticatedHierarchyLevelIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ai-suggest': typeof AuthenticatedAiSuggestRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/encyclopedia': typeof AuthenticatedEncyclopediaRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/modeler': typeof AuthenticatedModelerRoute
  '/node-er': typeof AuthenticatedNodeErRoute
  '/process-map': typeof AuthenticatedProcessMapRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/admin/control-center': typeof AuthenticatedAdminControlCenterRoute
  '/admin/entities-er': typeof AuthenticatedAdminEntitiesErRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/node-taxonomy': typeof AuthenticatedAdminNodeTaxonomyRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/confirm-signup': typeof ApiPublicConfirmSignupRoute
  '/api/public/notify-new-signup': typeof ApiPublicNotifyNewSignupRoute
  '/api/public/send-welcome-confirm': typeof ApiPublicSendWelcomeConfirmRoute
  '/api/public/validate-email': typeof ApiPublicValidateEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/hierarchy/$level/$id': typeof AuthenticatedHierarchyLevelIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/ai-suggest': typeof AuthenticatedAiSuggestRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/encyclopedia': typeof AuthenticatedEncyclopediaRoute
  '/_authenticated/engine': typeof AuthenticatedEngineRoute
  '/_authenticated/entities': typeof AuthenticatedEntitiesRoute
  '/_authenticated/modeler': typeof AuthenticatedModelerRoute
  '/_authenticated/node-er': typeof AuthenticatedNodeErRoute
  '/_authenticated/process-map': typeof AuthenticatedProcessMapRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/_authenticated/admin/control-center': typeof AuthenticatedAdminControlCenterRoute
  '/_authenticated/admin/entities-er': typeof AuthenticatedAdminEntitiesErRoute
  '/_authenticated/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/_authenticated/admin/node-taxonomy': typeof AuthenticatedAdminNodeTaxonomyRoute
  '/_authenticated/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/confirm-signup': typeof ApiPublicConfirmSignupRoute
  '/api/public/notify-new-signup': typeof ApiPublicNotifyNewSignupRoute
  '/api/public/send-welcome-confirm': typeof ApiPublicSendWelcomeConfirmRoute
  '/api/public/validate-email': typeof ApiPublicValidateEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/hierarchy/$level/$id': typeof AuthenticatedHierarchyLevelIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/ai-suggest'
    | '/changelog'
    | '/dashboard'
    | '/database'
    | '/encyclopedia'
    | '/engine'
    | '/entities'
    | '/modeler'
    | '/node-er'
    | '/process-map'
    | '/webhooks'
    | '/email/unsubscribe'
    | '/invite/accept'
    | '/onboarding/confirm'
    | '/admin/control-center'
    | '/admin/entities-er'
    | '/admin/governance'
    | '/admin/node-taxonomy'
    | '/admin/tenant'
    | '/admin/users'
    | '/api/public/accept-invite'
    | '/api/public/confirm-signup'
    | '/api/public/notify-new-signup'
    | '/api/public/send-welcome-confirm'
    | '/api/public/validate-email'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/hierarchy/$level/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/ai-suggest'
    | '/changelog'
    | '/dashboard'
    | '/database'
    | '/encyclopedia'
    | '/engine'
    | '/entities'
    | '/modeler'
    | '/node-er'
    | '/process-map'
    | '/webhooks'
    | '/email/unsubscribe'
    | '/invite/accept'
    | '/onboarding/confirm'
    | '/admin/control-center'
    | '/admin/entities-er'
    | '/admin/governance'
    | '/admin/node-taxonomy'
    | '/admin/tenant'
    | '/admin/users'
    | '/api/public/accept-invite'
    | '/api/public/confirm-signup'
    | '/api/public/notify-new-signup'
    | '/api/public/send-welcome-confirm'
    | '/api/public/validate-email'
    | '/lovable/email/suppression'
    | '/admin'
    | '/hierarchy/$level/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/_authenticated/ai-suggest'
    | '/_authenticated/changelog'
    | '/_authenticated/dashboard'
    | '/_authenticated/database'
    | '/_authenticated/encyclopedia'
    | '/_authenticated/engine'
    | '/_authenticated/entities'
    | '/_authenticated/modeler'
    | '/_authenticated/node-er'
    | '/_authenticated/process-map'
    | '/_authenticated/webhooks'
    | '/email/unsubscribe'
    | '/invite/accept'
    | '/onboarding/confirm'
    | '/_authenticated/admin/control-center'
    | '/_authenticated/admin/entities-er'
    | '/_authenticated/admin/governance'
    | '/_authenticated/admin/node-taxonomy'
    | '/_authenticated/admin/tenant'
    | '/_authenticated/admin/users'
    | '/api/public/accept-invite'
    | '/api/public/confirm-signup'
    | '/api/public/notify-new-signup'
    | '/api/public/send-welcome-confirm'
    | '/api/public/validate-email'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/hierarchy/$level/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  OnboardingConfirmRoute: typeof OnboardingConfirmRoute
  ApiPublicAcceptInviteRoute: typeof ApiPublicAcceptInviteRoute
  ApiPublicConfirmSignupRoute: typeof ApiPublicConfirmSignupRoute
  ApiPublicNotifyNewSignupRoute: typeof ApiPublicNotifyNewSignupRoute
  ApiPublicSendWelcomeConfirmRoute: typeof ApiPublicSendWelcomeConfirmRoute
  ApiPublicValidateEmailRoute: typeof ApiPublicValidateEmailRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/confirm': {
      id: '/onboarding/confirm'
      path: '/onboarding/confirm'
      fullPath: '/onboarding/confirm'
      preLoaderRoute: typeof OnboardingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/process-map': {
      id: '/_authenticated/process-map'
      path: '/process-map'
      fullPath: '/process-map'
      preLoaderRoute: typeof AuthenticatedProcessMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/node-er': {
      id: '/_authenticated/node-er'
      path: '/node-er'
      fullPath: '/node-er'
      preLoaderRoute: typeof AuthenticatedNodeErRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modeler': {
      id: '/_authenticated/modeler'
      path: '/modeler'
      fullPath: '/modeler'
      preLoaderRoute: typeof AuthenticatedModelerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entities': {
      id: '/_authenticated/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AuthenticatedEntitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engine': {
      id: '/_authenticated/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof AuthenticatedEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encyclopedia': {
      id: '/_authenticated/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof AuthenticatedEncyclopediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-suggest': {
      id: '/_authenticated/ai-suggest'
      path: '/ai-suggest'
      fullPath: '/ai-suggest'
      preLoaderRoute: typeof AuthenticatedAiSuggestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/validate-email': {
      id: '/api/public/validate-email'
      path: '/api/public/validate-email'
      fullPath: '/api/public/validate-email'
      preLoaderRoute: typeof ApiPublicValidateEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-welcome-confirm': {
      id: '/api/public/send-welcome-confirm'
      path: '/api/public/send-welcome-confirm'
      fullPath: '/api/public/send-welcome-confirm'
      preLoaderRoute: typeof ApiPublicSendWelcomeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-new-signup': {
      id: '/api/public/notify-new-signup'
      path: '/api/public/notify-new-signup'
      fullPath: '/api/public/notify-new-signup'
      preLoaderRoute: typeof ApiPublicNotifyNewSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm-signup': {
      id: '/api/public/confirm-signup'
      path: '/api/public/confirm-signup'
      fullPath: '/api/public/confirm-signup'
      preLoaderRoute: typeof ApiPublicConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-invite': {
      id: '/api/public/accept-invite'
      path: '/api/public/accept-invite'
      fullPath: '/api/public/accept-invite'
      preLoaderRoute: typeof ApiPublicAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenant': {
      id: '/_authenticated/admin/tenant'
      path: '/admin/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AuthenticatedAdminTenantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/node-taxonomy': {
      id: '/_authenticated/admin/node-taxonomy'
      path: '/admin/node-taxonomy'
      fullPath: '/admin/node-taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminNodeTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/governance': {
      id: '/_authenticated/admin/governance'
      path: '/admin/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AuthenticatedAdminGovernanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/entities-er': {
      id: '/_authenticated/admin/entities-er'
      path: '/admin/entities-er'
      fullPath: '/admin/entities-er'
      preLoaderRoute: typeof AuthenticatedAdminEntitiesErRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/control-center': {
      id: '/_authenticated/admin/control-center'
      path: '/admin/control-center'
      fullPath: '/admin/control-center'
      preLoaderRoute: typeof AuthenticatedAdminControlCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hierarchy/$level/$id': {
      id: '/_authenticated/hierarchy/$level/$id'
      path: '/hierarchy/$level/$id'
      fullPath: '/hierarchy/$level/$id'
      preLoaderRoute: typeof AuthenticatedHierarchyLevelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiSuggestRoute: typeof AuthenticatedAiSuggestRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedEncyclopediaRoute: typeof AuthenticatedEncyclopediaRoute
  AuthenticatedEngineRoute: typeof AuthenticatedEngineRoute
  AuthenticatedEntitiesRoute: typeof AuthenticatedEntitiesRoute
  AuthenticatedModelerRoute: typeof AuthenticatedModelerRoute
  AuthenticatedNodeErRoute: typeof AuthenticatedNodeErRoute
  AuthenticatedProcessMapRoute: typeof AuthenticatedProcessMapRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedAdminControlCenterRoute: typeof AuthenticatedAdminControlCenterRoute
  AuthenticatedAdminEntitiesErRoute: typeof AuthenticatedAdminEntitiesErRoute
  AuthenticatedAdminGovernanceRoute: typeof AuthenticatedAdminGovernanceRoute
  AuthenticatedAdminNodeTaxonomyRoute: typeof AuthenticatedAdminNodeTaxonomyRoute
  AuthenticatedAdminTenantRoute: typeof AuthenticatedAdminTenantRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedHierarchyLevelIdRoute: typeof AuthenticatedHierarchyLevelIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiSuggestRoute: AuthenticatedAiSuggestRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedEncyclopediaRoute: AuthenticatedEncyclopediaRoute,
  AuthenticatedEngineRoute: AuthenticatedEngineRoute,
  AuthenticatedEntitiesRoute: AuthenticatedEntitiesRoute,
  AuthenticatedModelerRoute: AuthenticatedModelerRoute,
  AuthenticatedNodeErRoute: AuthenticatedNodeErRoute,
  AuthenticatedProcessMapRoute: AuthenticatedProcessMapRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedAdminControlCenterRoute: AuthenticatedAdminControlCenterRoute,
  AuthenticatedAdminEntitiesErRoute: AuthenticatedAdminEntitiesErRoute,
  AuthenticatedAdminGovernanceRoute: AuthenticatedAdminGovernanceRoute,
  AuthenticatedAdminNodeTaxonomyRoute: AuthenticatedAdminNodeTaxonomyRoute,
  AuthenticatedAdminTenantRoute: AuthenticatedAdminTenantRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedHierarchyLevelIdRoute: AuthenticatedHierarchyLevelIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  OnboardingConfirmRoute: OnboardingConfirmRoute,
  ApiPublicAcceptInviteRoute: ApiPublicAcceptInviteRoute,
  ApiPublicConfirmSignupRoute: ApiPublicConfirmSignupRoute,
  ApiPublicNotifyNewSignupRoute: ApiPublicNotifyNewSignupRoute,
  ApiPublicSendWelcomeConfirmRoute: ApiPublicSendWelcomeConfirmRoute,
  ApiPublicValidateEmailRoute: ApiPublicValidateEmailRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
